### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-partnership/www.open-spending.eu#1]
* [x] Change `karolisgranickas` to Team Maintainer https://github.com/orgs/open-contracting-partnership/teams/coalition/members
* [ ] Replace the Contact Us and Join Us forms with buttons linking to Google/SurveyMonkey forms
* [x] Register the new domain under OCP’s GoDaddy account
* [x] On GoDaddy, create a CNAME for the www subdomain to open-contracting-partnership.github.io
* [x] On GoDaddy, for the apex domain (no www), configure redirection to the www subdomain within GoDaddy’s interface. If not, then we can add four A records [as documented here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)
* [x] On GitHub, set the domain including the `www.` part: https://github.com/open-contracting-partnership/coalition/settings/pages
* [x] On GitHub, ensure that “Enforce HTTPS” is checked at https://github.com/open-contracting-partnership/coalition/settings/pages
* [x] Change the `<base>` tag to `href="/"` in all files
* [x] Rename the repository to the domain name (with www)
* [x] Update stylesheet for RFF article

cc @karolisgranickas @georgneu
